package com.yb.entity;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Miniprogram.proto

public final class Miniprogram {
  private Miniprogram() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CJdZtMiniProgramReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .CJdZtMiniProgramData vData = 1;
    /**
     * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
     */
    java.util.List<CJdZtMiniProgramData>
        getVDataList();
    /**
     * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
     */
    CJdZtMiniProgramData getVData(int index);
    /**
     * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
     */
    int getVDataCount();
    /**
     * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
     */
    java.util.List<? extends CJdZtMiniProgramDataOrBuilder>
        getVDataOrBuilderList();
    /**
     * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
     */
    CJdZtMiniProgramDataOrBuilder getVDataOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code CJdZtMiniProgramReq}
   */
  public static final class CJdZtMiniProgramReq extends
      com.google.protobuf.GeneratedMessage
      implements CJdZtMiniProgramReqOrBuilder {
    // Use CJdZtMiniProgramReq.newBuilder() to construct.
    private CJdZtMiniProgramReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CJdZtMiniProgramReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CJdZtMiniProgramReq defaultInstance;
    public static CJdZtMiniProgramReq getDefaultInstance() {
      return defaultInstance;
    }

    public CJdZtMiniProgramReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CJdZtMiniProgramReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                vData_ = new java.util.ArrayList<CJdZtMiniProgramData>();
                mutable_bitField0_ |= 0x00000001;
              }
              vData_.add(input.readMessage(CJdZtMiniProgramData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          vData_ = java.util.Collections.unmodifiableList(vData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Miniprogram.internal_static_CJdZtMiniProgramReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Miniprogram.internal_static_CJdZtMiniProgramReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CJdZtMiniProgramReq.class, Builder.class);
    }

    public static com.google.protobuf.Parser<CJdZtMiniProgramReq> PARSER =
        new com.google.protobuf.AbstractParser<CJdZtMiniProgramReq>() {
      public CJdZtMiniProgramReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CJdZtMiniProgramReq(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CJdZtMiniProgramReq> getParserForType() {
      return PARSER;
    }

    // repeated .CJdZtMiniProgramData vData = 1;
    public static final int VDATA_FIELD_NUMBER = 1;
    private java.util.List<CJdZtMiniProgramData> vData_;
    /**
     * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
     */
    public java.util.List<CJdZtMiniProgramData> getVDataList() {
      return vData_;
    }
    /**
     * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
     */
    public java.util.List<? extends CJdZtMiniProgramDataOrBuilder>
        getVDataOrBuilderList() {
      return vData_;
    }
    /**
     * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
     */
    public int getVDataCount() {
      return vData_.size();
    }
    /**
     * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
     */
    public CJdZtMiniProgramData getVData(int index) {
      return vData_.get(index);
    }
    /**
     * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
     */
    public CJdZtMiniProgramDataOrBuilder getVDataOrBuilder(
        int index) {
      return vData_.get(index);
    }

    private void initFields() {
      vData_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < vData_.size(); i++) {
        output.writeMessage(1, vData_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < vData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, vData_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CJdZtMiniProgramReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CJdZtMiniProgramReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CJdZtMiniProgramReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CJdZtMiniProgramReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CJdZtMiniProgramReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CJdZtMiniProgramReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CJdZtMiniProgramReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CJdZtMiniProgramReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CJdZtMiniProgramReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CJdZtMiniProgramReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CJdZtMiniProgramReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CJdZtMiniProgramReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CJdZtMiniProgramReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Miniprogram.internal_static_CJdZtMiniProgramReq_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Miniprogram.internal_static_CJdZtMiniProgramReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CJdZtMiniProgramReq.class, Builder.class);
      }

      // Construct using Miniprogram.CJdZtMiniProgramReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getVDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (vDataBuilder_ == null) {
          vData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          vDataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Miniprogram.internal_static_CJdZtMiniProgramReq_descriptor;
      }

      public CJdZtMiniProgramReq getDefaultInstanceForType() {
        return CJdZtMiniProgramReq.getDefaultInstance();
      }

      public CJdZtMiniProgramReq build() {
        CJdZtMiniProgramReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CJdZtMiniProgramReq buildPartial() {
        CJdZtMiniProgramReq result = new CJdZtMiniProgramReq(this);
        int from_bitField0_ = bitField0_;
        if (vDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            vData_ = java.util.Collections.unmodifiableList(vData_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.vData_ = vData_;
        } else {
          result.vData_ = vDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CJdZtMiniProgramReq) {
          return mergeFrom((CJdZtMiniProgramReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CJdZtMiniProgramReq other) {
        if (other == CJdZtMiniProgramReq.getDefaultInstance()) return this;
        if (vDataBuilder_ == null) {
          if (!other.vData_.isEmpty()) {
            if (vData_.isEmpty()) {
              vData_ = other.vData_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureVDataIsMutable();
              vData_.addAll(other.vData_);
            }
            onChanged();
          }
        } else {
          if (!other.vData_.isEmpty()) {
            if (vDataBuilder_.isEmpty()) {
              vDataBuilder_.dispose();
              vDataBuilder_ = null;
              vData_ = other.vData_;
              bitField0_ = (bitField0_ & ~0x00000001);
              vDataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getVDataFieldBuilder() : null;
            } else {
              vDataBuilder_.addAllMessages(other.vData_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CJdZtMiniProgramReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CJdZtMiniProgramReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .CJdZtMiniProgramData vData = 1;
      private java.util.List<CJdZtMiniProgramData> vData_ =
        java.util.Collections.emptyList();
      private void ensureVDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          vData_ = new java.util.ArrayList<CJdZtMiniProgramData>(vData_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          CJdZtMiniProgramData, CJdZtMiniProgramData.Builder, CJdZtMiniProgramDataOrBuilder> vDataBuilder_;

      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public java.util.List<CJdZtMiniProgramData> getVDataList() {
        if (vDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(vData_);
        } else {
          return vDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public int getVDataCount() {
        if (vDataBuilder_ == null) {
          return vData_.size();
        } else {
          return vDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public CJdZtMiniProgramData getVData(int index) {
        if (vDataBuilder_ == null) {
          return vData_.get(index);
        } else {
          return vDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public Builder setVData(
          int index, CJdZtMiniProgramData value) {
        if (vDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVDataIsMutable();
          vData_.set(index, value);
          onChanged();
        } else {
          vDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public Builder setVData(
          int index, CJdZtMiniProgramData.Builder builderForValue) {
        if (vDataBuilder_ == null) {
          ensureVDataIsMutable();
          vData_.set(index, builderForValue.build());
          onChanged();
        } else {
          vDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public Builder addVData(CJdZtMiniProgramData value) {
        if (vDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVDataIsMutable();
          vData_.add(value);
          onChanged();
        } else {
          vDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public Builder addVData(
          int index, CJdZtMiniProgramData value) {
        if (vDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVDataIsMutable();
          vData_.add(index, value);
          onChanged();
        } else {
          vDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public Builder addVData(
          CJdZtMiniProgramData.Builder builderForValue) {
        if (vDataBuilder_ == null) {
          ensureVDataIsMutable();
          vData_.add(builderForValue.build());
          onChanged();
        } else {
          vDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public Builder addVData(
          int index, CJdZtMiniProgramData.Builder builderForValue) {
        if (vDataBuilder_ == null) {
          ensureVDataIsMutable();
          vData_.add(index, builderForValue.build());
          onChanged();
        } else {
          vDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public Builder addAllVData(
          Iterable<? extends CJdZtMiniProgramData> values) {
        if (vDataBuilder_ == null) {
          ensureVDataIsMutable();
          super.addAll(values, vData_);
          onChanged();
        } else {
          vDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public Builder clearVData() {
        if (vDataBuilder_ == null) {
          vData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          vDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public Builder removeVData(int index) {
        if (vDataBuilder_ == null) {
          ensureVDataIsMutable();
          vData_.remove(index);
          onChanged();
        } else {
          vDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public CJdZtMiniProgramData.Builder getVDataBuilder(
          int index) {
        return getVDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public CJdZtMiniProgramDataOrBuilder getVDataOrBuilder(
          int index) {
        if (vDataBuilder_ == null) {
          return vData_.get(index);  } else {
          return vDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public java.util.List<? extends CJdZtMiniProgramDataOrBuilder>
           getVDataOrBuilderList() {
        if (vDataBuilder_ != null) {
          return vDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(vData_);
        }
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public CJdZtMiniProgramData.Builder addVDataBuilder() {
        return getVDataFieldBuilder().addBuilder(
            CJdZtMiniProgramData.getDefaultInstance());
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public CJdZtMiniProgramData.Builder addVDataBuilder(
          int index) {
        return getVDataFieldBuilder().addBuilder(
            index, CJdZtMiniProgramData.getDefaultInstance());
      }
      /**
       * <code>repeated .CJdZtMiniProgramData vData = 1;</code>
       */
      public java.util.List<CJdZtMiniProgramData.Builder>
           getVDataBuilderList() {
        return getVDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          CJdZtMiniProgramData, CJdZtMiniProgramData.Builder, CJdZtMiniProgramDataOrBuilder>
          getVDataFieldBuilder() {
        if (vDataBuilder_ == null) {
          vDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              CJdZtMiniProgramData, CJdZtMiniProgramData.Builder, CJdZtMiniProgramDataOrBuilder>(
                  vData_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          vData_ = null;
        }
        return vDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:CJdZtMiniProgramReq)
    }

    static {
      defaultInstance = new CJdZtMiniProgramReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CJdZtMiniProgramReq)
  }

  public interface CJdZtMiniProgramDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes sOriginalId = 1;
    /**
     * <code>optional bytes sOriginalId = 1;</code>
     */
    boolean hasSOriginalId();
    /**
     * <code>optional bytes sOriginalId = 1;</code>
     */
    com.google.protobuf.ByteString getSOriginalId();

    // optional bytes sAppId = 2;
    /**
     * <code>optional bytes sAppId = 2;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    boolean hasSAppId();
    /**
     * <code>optional bytes sAppId = 2;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    com.google.protobuf.ByteString getSAppId();

    // optional bytes sAccessToken = 3;
    /**
     * <code>optional bytes sAccessToken = 3;</code>
     */
    boolean hasSAccessToken();
    /**
     * <code>optional bytes sAccessToken = 3;</code>
     */
    com.google.protobuf.ByteString getSAccessToken();

    // optional uint64 ddwValidBeginTime = 4;
    /**
     * <code>optional uint64 ddwValidBeginTime = 4;</code>
     */
    boolean hasDdwValidBeginTime();
    /**
     * <code>optional uint64 ddwValidBeginTime = 4;</code>
     */
    long getDdwValidBeginTime();

    // optional uint64 ddwValidEndTime = 5;
    /**
     * <code>optional uint64 ddwValidEndTime = 5;</code>
     */
    boolean hasDdwValidEndTime();
    /**
     * <code>optional uint64 ddwValidEndTime = 5;</code>
     */
    long getDdwValidEndTime();
  }
  /**
   * Protobuf type {@code CJdZtMiniProgramData}
   */
  public static final class CJdZtMiniProgramData extends
      com.google.protobuf.GeneratedMessage
      implements CJdZtMiniProgramDataOrBuilder {
    // Use CJdZtMiniProgramData.newBuilder() to construct.
    private CJdZtMiniProgramData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CJdZtMiniProgramData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CJdZtMiniProgramData defaultInstance;
    public static CJdZtMiniProgramData getDefaultInstance() {
      return defaultInstance;
    }

    public CJdZtMiniProgramData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CJdZtMiniProgramData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sOriginalId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sAppId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              sAccessToken_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ddwValidBeginTime_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              ddwValidEndTime_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Miniprogram.internal_static_CJdZtMiniProgramData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Miniprogram.internal_static_CJdZtMiniProgramData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CJdZtMiniProgramData.class, Builder.class);
    }

    public static com.google.protobuf.Parser<CJdZtMiniProgramData> PARSER =
        new com.google.protobuf.AbstractParser<CJdZtMiniProgramData>() {
      public CJdZtMiniProgramData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CJdZtMiniProgramData(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CJdZtMiniProgramData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes sOriginalId = 1;
    public static final int SORIGINALID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString sOriginalId_;
    /**
     * <code>optional bytes sOriginalId = 1;</code>
     */
    public boolean hasSOriginalId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes sOriginalId = 1;</code>
     */
    public com.google.protobuf.ByteString getSOriginalId() {
      return sOriginalId_;
    }

    // optional bytes sAppId = 2;
    public static final int SAPPID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString sAppId_;
    /**
     * <code>optional bytes sAppId = 2;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public boolean hasSAppId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes sAppId = 2;</code>
     *
     * <pre>
     * 
     * </pre>
     */
    public com.google.protobuf.ByteString getSAppId() {
      return sAppId_;
    }

    // optional bytes sAccessToken = 3;
    public static final int SACCESSTOKEN_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString sAccessToken_;
    /**
     * <code>optional bytes sAccessToken = 3;</code>
     */
    public boolean hasSAccessToken() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes sAccessToken = 3;</code>
     */
    public com.google.protobuf.ByteString getSAccessToken() {
      return sAccessToken_;
    }

    // optional uint64 ddwValidBeginTime = 4;
    public static final int DDWVALIDBEGINTIME_FIELD_NUMBER = 4;
    private long ddwValidBeginTime_;
    /**
     * <code>optional uint64 ddwValidBeginTime = 4;</code>
     */
    public boolean hasDdwValidBeginTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 ddwValidBeginTime = 4;</code>
     */
    public long getDdwValidBeginTime() {
      return ddwValidBeginTime_;
    }

    // optional uint64 ddwValidEndTime = 5;
    public static final int DDWVALIDENDTIME_FIELD_NUMBER = 5;
    private long ddwValidEndTime_;
    /**
     * <code>optional uint64 ddwValidEndTime = 5;</code>
     */
    public boolean hasDdwValidEndTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint64 ddwValidEndTime = 5;</code>
     */
    public long getDdwValidEndTime() {
      return ddwValidEndTime_;
    }

    private void initFields() {
      sOriginalId_ = com.google.protobuf.ByteString.EMPTY;
      sAppId_ = com.google.protobuf.ByteString.EMPTY;
      sAccessToken_ = com.google.protobuf.ByteString.EMPTY;
      ddwValidBeginTime_ = 0L;
      ddwValidEndTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, sOriginalId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, sAppId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, sAccessToken_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, ddwValidBeginTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, ddwValidEndTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, sOriginalId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, sAppId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, sAccessToken_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, ddwValidBeginTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, ddwValidEndTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CJdZtMiniProgramData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CJdZtMiniProgramData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CJdZtMiniProgramData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CJdZtMiniProgramData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CJdZtMiniProgramData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CJdZtMiniProgramData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CJdZtMiniProgramData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CJdZtMiniProgramData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CJdZtMiniProgramData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CJdZtMiniProgramData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CJdZtMiniProgramData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CJdZtMiniProgramData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CJdZtMiniProgramDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Miniprogram.internal_static_CJdZtMiniProgramData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Miniprogram.internal_static_CJdZtMiniProgramData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CJdZtMiniProgramData.class, Builder.class);
      }

      // Construct using Miniprogram.CJdZtMiniProgramData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sOriginalId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        sAppId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        sAccessToken_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        ddwValidBeginTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        ddwValidEndTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Miniprogram.internal_static_CJdZtMiniProgramData_descriptor;
      }

      public CJdZtMiniProgramData getDefaultInstanceForType() {
        return CJdZtMiniProgramData.getDefaultInstance();
      }

      public CJdZtMiniProgramData build() {
        CJdZtMiniProgramData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CJdZtMiniProgramData buildPartial() {
        CJdZtMiniProgramData result = new CJdZtMiniProgramData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sOriginalId_ = sOriginalId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sAppId_ = sAppId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sAccessToken_ = sAccessToken_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ddwValidBeginTime_ = ddwValidBeginTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ddwValidEndTime_ = ddwValidEndTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CJdZtMiniProgramData) {
          return mergeFrom((CJdZtMiniProgramData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CJdZtMiniProgramData other) {
        if (other == CJdZtMiniProgramData.getDefaultInstance()) return this;
        if (other.hasSOriginalId()) {
          setSOriginalId(other.getSOriginalId());
        }
        if (other.hasSAppId()) {
          setSAppId(other.getSAppId());
        }
        if (other.hasSAccessToken()) {
          setSAccessToken(other.getSAccessToken());
        }
        if (other.hasDdwValidBeginTime()) {
          setDdwValidBeginTime(other.getDdwValidBeginTime());
        }
        if (other.hasDdwValidEndTime()) {
          setDdwValidEndTime(other.getDdwValidEndTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CJdZtMiniProgramData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CJdZtMiniProgramData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes sOriginalId = 1;
      private com.google.protobuf.ByteString sOriginalId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes sOriginalId = 1;</code>
       */
      public boolean hasSOriginalId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes sOriginalId = 1;</code>
       */
      public com.google.protobuf.ByteString getSOriginalId() {
        return sOriginalId_;
      }
      /**
       * <code>optional bytes sOriginalId = 1;</code>
       */
      public Builder setSOriginalId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sOriginalId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes sOriginalId = 1;</code>
       */
      public Builder clearSOriginalId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sOriginalId_ = getDefaultInstance().getSOriginalId();
        onChanged();
        return this;
      }

      // optional bytes sAppId = 2;
      private com.google.protobuf.ByteString sAppId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes sAppId = 2;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public boolean hasSAppId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes sAppId = 2;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public com.google.protobuf.ByteString getSAppId() {
        return sAppId_;
      }
      /**
       * <code>optional bytes sAppId = 2;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder setSAppId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sAppId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes sAppId = 2;</code>
       *
       * <pre>
       * 
       * </pre>
       */
      public Builder clearSAppId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sAppId_ = getDefaultInstance().getSAppId();
        onChanged();
        return this;
      }

      // optional bytes sAccessToken = 3;
      private com.google.protobuf.ByteString sAccessToken_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes sAccessToken = 3;</code>
       */
      public boolean hasSAccessToken() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes sAccessToken = 3;</code>
       */
      public com.google.protobuf.ByteString getSAccessToken() {
        return sAccessToken_;
      }
      /**
       * <code>optional bytes sAccessToken = 3;</code>
       */
      public Builder setSAccessToken(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sAccessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes sAccessToken = 3;</code>
       */
      public Builder clearSAccessToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sAccessToken_ = getDefaultInstance().getSAccessToken();
        onChanged();
        return this;
      }

      // optional uint64 ddwValidBeginTime = 4;
      private long ddwValidBeginTime_ ;
      /**
       * <code>optional uint64 ddwValidBeginTime = 4;</code>
       */
      public boolean hasDdwValidBeginTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 ddwValidBeginTime = 4;</code>
       */
      public long getDdwValidBeginTime() {
        return ddwValidBeginTime_;
      }
      /**
       * <code>optional uint64 ddwValidBeginTime = 4;</code>
       */
      public Builder setDdwValidBeginTime(long value) {
        bitField0_ |= 0x00000008;
        ddwValidBeginTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ddwValidBeginTime = 4;</code>
       */
      public Builder clearDdwValidBeginTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ddwValidBeginTime_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 ddwValidEndTime = 5;
      private long ddwValidEndTime_ ;
      /**
       * <code>optional uint64 ddwValidEndTime = 5;</code>
       */
      public boolean hasDdwValidEndTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 ddwValidEndTime = 5;</code>
       */
      public long getDdwValidEndTime() {
        return ddwValidEndTime_;
      }
      /**
       * <code>optional uint64 ddwValidEndTime = 5;</code>
       */
      public Builder setDdwValidEndTime(long value) {
        bitField0_ |= 0x00000010;
        ddwValidEndTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ddwValidEndTime = 5;</code>
       */
      public Builder clearDdwValidEndTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ddwValidEndTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CJdZtMiniProgramData)
    }

    static {
      defaultInstance = new CJdZtMiniProgramData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CJdZtMiniProgramData)
  }

  public interface CJdZtReturnDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 iRet = 1;
    /**
     * <code>required int32 iRet = 1;</code>
     */
    boolean hasIRet();
    /**
     * <code>required int32 iRet = 1;</code>
     */
    int getIRet();

    // required bytes sMsg = 2;
    /**
     * <code>required bytes sMsg = 2;</code>
     */
    boolean hasSMsg();
    /**
     * <code>required bytes sMsg = 2;</code>
     */
    com.google.protobuf.ByteString getSMsg();
  }
  /**
   * Protobuf type {@code CJdZtReturnData}
   */
  public static final class CJdZtReturnData extends
      com.google.protobuf.GeneratedMessage
      implements CJdZtReturnDataOrBuilder {
    // Use CJdZtReturnData.newBuilder() to construct.
    private CJdZtReturnData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CJdZtReturnData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CJdZtReturnData defaultInstance;
    public static CJdZtReturnData getDefaultInstance() {
      return defaultInstance;
    }

    public CJdZtReturnData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CJdZtReturnData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              iRet_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Miniprogram.internal_static_CJdZtReturnData_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Miniprogram.internal_static_CJdZtReturnData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CJdZtReturnData.class, Builder.class);
    }

    public static com.google.protobuf.Parser<CJdZtReturnData> PARSER =
        new com.google.protobuf.AbstractParser<CJdZtReturnData>() {
      public CJdZtReturnData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CJdZtReturnData(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CJdZtReturnData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 iRet = 1;
    public static final int IRET_FIELD_NUMBER = 1;
    private int iRet_;
    /**
     * <code>required int32 iRet = 1;</code>
     */
    public boolean hasIRet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 iRet = 1;</code>
     */
    public int getIRet() {
      return iRet_;
    }

    // required bytes sMsg = 2;
    public static final int SMSG_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString sMsg_;
    /**
     * <code>required bytes sMsg = 2;</code>
     */
    public boolean hasSMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes sMsg = 2;</code>
     */
    public com.google.protobuf.ByteString getSMsg() {
      return sMsg_;
    }

    private void initFields() {
      iRet_ = 0;
      sMsg_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIRet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, iRet_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, sMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iRet_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, sMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CJdZtReturnData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CJdZtReturnData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CJdZtReturnData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CJdZtReturnData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CJdZtReturnData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CJdZtReturnData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CJdZtReturnData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CJdZtReturnData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CJdZtReturnData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CJdZtReturnData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CJdZtReturnData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CJdZtReturnData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CJdZtReturnDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Miniprogram.internal_static_CJdZtReturnData_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Miniprogram.internal_static_CJdZtReturnData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CJdZtReturnData.class, Builder.class);
      }

      // Construct using Miniprogram.CJdZtReturnData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        iRet_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sMsg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Miniprogram.internal_static_CJdZtReturnData_descriptor;
      }

      public CJdZtReturnData getDefaultInstanceForType() {
        return CJdZtReturnData.getDefaultInstance();
      }

      public CJdZtReturnData build() {
        CJdZtReturnData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CJdZtReturnData buildPartial() {
        CJdZtReturnData result = new CJdZtReturnData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.iRet_ = iRet_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sMsg_ = sMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CJdZtReturnData) {
          return mergeFrom((CJdZtReturnData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CJdZtReturnData other) {
        if (other == CJdZtReturnData.getDefaultInstance()) return this;
        if (other.hasIRet()) {
          setIRet(other.getIRet());
        }
        if (other.hasSMsg()) {
          setSMsg(other.getSMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIRet()) {
          
          return false;
        }
        if (!hasSMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CJdZtReturnData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CJdZtReturnData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 iRet = 1;
      private int iRet_ ;
      /**
       * <code>required int32 iRet = 1;</code>
       */
      public boolean hasIRet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 iRet = 1;</code>
       */
      public int getIRet() {
        return iRet_;
      }
      /**
       * <code>required int32 iRet = 1;</code>
       */
      public Builder setIRet(int value) {
        bitField0_ |= 0x00000001;
        iRet_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 iRet = 1;</code>
       */
      public Builder clearIRet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iRet_ = 0;
        onChanged();
        return this;
      }

      // required bytes sMsg = 2;
      private com.google.protobuf.ByteString sMsg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes sMsg = 2;</code>
       */
      public boolean hasSMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes sMsg = 2;</code>
       */
      public com.google.protobuf.ByteString getSMsg() {
        return sMsg_;
      }
      /**
       * <code>required bytes sMsg = 2;</code>
       */
      public Builder setSMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes sMsg = 2;</code>
       */
      public Builder clearSMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sMsg_ = getDefaultInstance().getSMsg();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CJdZtReturnData)
    }

    static {
      defaultInstance = new CJdZtReturnData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CJdZtReturnData)
  }

  public interface CJdZtMiniProgramRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .CJdZtReturnData oRet = 1;
    /**
     * <code>required .CJdZtReturnData oRet = 1;</code>
     */
    boolean hasORet();
    /**
     * <code>required .CJdZtReturnData oRet = 1;</code>
     */
    CJdZtReturnData getORet();
    /**
     * <code>required .CJdZtReturnData oRet = 1;</code>
     */
    CJdZtReturnDataOrBuilder getORetOrBuilder();

    // repeated bytes vOriginalId = 2;
    /**
     * <code>repeated bytes vOriginalId = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getVOriginalIdList();
    /**
     * <code>repeated bytes vOriginalId = 2;</code>
     */
    int getVOriginalIdCount();
    /**
     * <code>repeated bytes vOriginalId = 2;</code>
     */
    com.google.protobuf.ByteString getVOriginalId(int index);
  }
  /**
   * Protobuf type {@code CJdZtMiniProgramResp}
   */
  public static final class CJdZtMiniProgramResp extends
      com.google.protobuf.GeneratedMessage
      implements CJdZtMiniProgramRespOrBuilder {
    // Use CJdZtMiniProgramResp.newBuilder() to construct.
    private CJdZtMiniProgramResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CJdZtMiniProgramResp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CJdZtMiniProgramResp defaultInstance;
    public static CJdZtMiniProgramResp getDefaultInstance() {
      return defaultInstance;
    }

    public CJdZtMiniProgramResp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CJdZtMiniProgramResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              CJdZtReturnData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = oRet_.toBuilder();
              }
              oRet_ = input.readMessage(CJdZtReturnData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(oRet_);
                oRet_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                vOriginalId_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              vOriginalId_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          vOriginalId_ = java.util.Collections.unmodifiableList(vOriginalId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Miniprogram.internal_static_CJdZtMiniProgramResp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Miniprogram.internal_static_CJdZtMiniProgramResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CJdZtMiniProgramResp.class, Builder.class);
    }

    public static com.google.protobuf.Parser<CJdZtMiniProgramResp> PARSER =
        new com.google.protobuf.AbstractParser<CJdZtMiniProgramResp>() {
      public CJdZtMiniProgramResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CJdZtMiniProgramResp(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CJdZtMiniProgramResp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .CJdZtReturnData oRet = 1;
    public static final int ORET_FIELD_NUMBER = 1;
    private CJdZtReturnData oRet_;
    /**
     * <code>required .CJdZtReturnData oRet = 1;</code>
     */
    public boolean hasORet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .CJdZtReturnData oRet = 1;</code>
     */
    public CJdZtReturnData getORet() {
      return oRet_;
    }
    /**
     * <code>required .CJdZtReturnData oRet = 1;</code>
     */
    public CJdZtReturnDataOrBuilder getORetOrBuilder() {
      return oRet_;
    }

    // repeated bytes vOriginalId = 2;
    public static final int VORIGINALID_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> vOriginalId_;
    /**
     * <code>repeated bytes vOriginalId = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getVOriginalIdList() {
      return vOriginalId_;
    }
    /**
     * <code>repeated bytes vOriginalId = 2;</code>
     */
    public int getVOriginalIdCount() {
      return vOriginalId_.size();
    }
    /**
     * <code>repeated bytes vOriginalId = 2;</code>
     */
    public com.google.protobuf.ByteString getVOriginalId(int index) {
      return vOriginalId_.get(index);
    }

    private void initFields() {
      oRet_ = CJdZtReturnData.getDefaultInstance();
      vOriginalId_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasORet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getORet().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, oRet_);
      }
      for (int i = 0; i < vOriginalId_.size(); i++) {
        output.writeBytes(2, vOriginalId_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, oRet_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < vOriginalId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(vOriginalId_.get(i));
        }
        size += dataSize;
        size += 1 * getVOriginalIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CJdZtMiniProgramResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CJdZtMiniProgramResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CJdZtMiniProgramResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CJdZtMiniProgramResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CJdZtMiniProgramResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CJdZtMiniProgramResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CJdZtMiniProgramResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CJdZtMiniProgramResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CJdZtMiniProgramResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CJdZtMiniProgramResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CJdZtMiniProgramResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CJdZtMiniProgramResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CJdZtMiniProgramRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Miniprogram.internal_static_CJdZtMiniProgramResp_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Miniprogram.internal_static_CJdZtMiniProgramResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CJdZtMiniProgramResp.class, Builder.class);
      }

      // Construct using Miniprogram.CJdZtMiniProgramResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getORetFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (oRetBuilder_ == null) {
          oRet_ = CJdZtReturnData.getDefaultInstance();
        } else {
          oRetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        vOriginalId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Miniprogram.internal_static_CJdZtMiniProgramResp_descriptor;
      }

      public CJdZtMiniProgramResp getDefaultInstanceForType() {
        return CJdZtMiniProgramResp.getDefaultInstance();
      }

      public CJdZtMiniProgramResp build() {
        CJdZtMiniProgramResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CJdZtMiniProgramResp buildPartial() {
        CJdZtMiniProgramResp result = new CJdZtMiniProgramResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (oRetBuilder_ == null) {
          result.oRet_ = oRet_;
        } else {
          result.oRet_ = oRetBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          vOriginalId_ = java.util.Collections.unmodifiableList(vOriginalId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.vOriginalId_ = vOriginalId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CJdZtMiniProgramResp) {
          return mergeFrom((CJdZtMiniProgramResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CJdZtMiniProgramResp other) {
        if (other == CJdZtMiniProgramResp.getDefaultInstance()) return this;
        if (other.hasORet()) {
          mergeORet(other.getORet());
        }
        if (!other.vOriginalId_.isEmpty()) {
          if (vOriginalId_.isEmpty()) {
            vOriginalId_ = other.vOriginalId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureVOriginalIdIsMutable();
            vOriginalId_.addAll(other.vOriginalId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasORet()) {
          
          return false;
        }
        if (!getORet().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CJdZtMiniProgramResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CJdZtMiniProgramResp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .CJdZtReturnData oRet = 1;
      private CJdZtReturnData oRet_ = CJdZtReturnData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          CJdZtReturnData, CJdZtReturnData.Builder, CJdZtReturnDataOrBuilder> oRetBuilder_;
      /**
       * <code>required .CJdZtReturnData oRet = 1;</code>
       */
      public boolean hasORet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .CJdZtReturnData oRet = 1;</code>
       */
      public CJdZtReturnData getORet() {
        if (oRetBuilder_ == null) {
          return oRet_;
        } else {
          return oRetBuilder_.getMessage();
        }
      }
      /**
       * <code>required .CJdZtReturnData oRet = 1;</code>
       */
      public Builder setORet(CJdZtReturnData value) {
        if (oRetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          oRet_ = value;
          onChanged();
        } else {
          oRetBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .CJdZtReturnData oRet = 1;</code>
       */
      public Builder setORet(
          CJdZtReturnData.Builder builderForValue) {
        if (oRetBuilder_ == null) {
          oRet_ = builderForValue.build();
          onChanged();
        } else {
          oRetBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .CJdZtReturnData oRet = 1;</code>
       */
      public Builder mergeORet(CJdZtReturnData value) {
        if (oRetBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              oRet_ != CJdZtReturnData.getDefaultInstance()) {
            oRet_ =
              CJdZtReturnData.newBuilder(oRet_).mergeFrom(value).buildPartial();
          } else {
            oRet_ = value;
          }
          onChanged();
        } else {
          oRetBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .CJdZtReturnData oRet = 1;</code>
       */
      public Builder clearORet() {
        if (oRetBuilder_ == null) {
          oRet_ = CJdZtReturnData.getDefaultInstance();
          onChanged();
        } else {
          oRetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .CJdZtReturnData oRet = 1;</code>
       */
      public CJdZtReturnData.Builder getORetBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getORetFieldBuilder().getBuilder();
      }
      /**
       * <code>required .CJdZtReturnData oRet = 1;</code>
       */
      public CJdZtReturnDataOrBuilder getORetOrBuilder() {
        if (oRetBuilder_ != null) {
          return oRetBuilder_.getMessageOrBuilder();
        } else {
          return oRet_;
        }
      }
      /**
       * <code>required .CJdZtReturnData oRet = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          CJdZtReturnData, CJdZtReturnData.Builder, CJdZtReturnDataOrBuilder>
          getORetFieldBuilder() {
        if (oRetBuilder_ == null) {
          oRetBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              CJdZtReturnData, CJdZtReturnData.Builder, CJdZtReturnDataOrBuilder>(
                  oRet_,
                  getParentForChildren(),
                  isClean());
          oRet_ = null;
        }
        return oRetBuilder_;
      }

      // repeated bytes vOriginalId = 2;
      private java.util.List<com.google.protobuf.ByteString> vOriginalId_ = java.util.Collections.emptyList();
      private void ensureVOriginalIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          vOriginalId_ = new java.util.ArrayList<com.google.protobuf.ByteString>(vOriginalId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes vOriginalId = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getVOriginalIdList() {
        return java.util.Collections.unmodifiableList(vOriginalId_);
      }
      /**
       * <code>repeated bytes vOriginalId = 2;</code>
       */
      public int getVOriginalIdCount() {
        return vOriginalId_.size();
      }
      /**
       * <code>repeated bytes vOriginalId = 2;</code>
       */
      public com.google.protobuf.ByteString getVOriginalId(int index) {
        return vOriginalId_.get(index);
      }
      /**
       * <code>repeated bytes vOriginalId = 2;</code>
       */
      public Builder setVOriginalId(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVOriginalIdIsMutable();
        vOriginalId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes vOriginalId = 2;</code>
       */
      public Builder addVOriginalId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVOriginalIdIsMutable();
        vOriginalId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes vOriginalId = 2;</code>
       */
      public Builder addAllVOriginalId(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureVOriginalIdIsMutable();
        super.addAll(values, vOriginalId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes vOriginalId = 2;</code>
       */
      public Builder clearVOriginalId() {
        vOriginalId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CJdZtMiniProgramResp)
    }

    static {
      defaultInstance = new CJdZtMiniProgramResp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CJdZtMiniProgramResp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CJdZtMiniProgramReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CJdZtMiniProgramReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CJdZtMiniProgramData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CJdZtMiniProgramData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CJdZtReturnData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CJdZtReturnData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CJdZtMiniProgramResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CJdZtMiniProgramResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021Miniprogram.proto\";\n\023CJdZtMiniProgramR" +
      "eq\022$\n\005vData\030\001 \003(\0132\025.CJdZtMiniProgramData" +
      "\"\205\001\n\024CJdZtMiniProgramData\022\023\n\013sOriginalId" +
      "\030\001 \001(\014\022\016\n\006sAppId\030\002 \001(\014\022\024\n\014sAccessToken\030\003" +
      " \001(\014\022\031\n\021ddwValidBeginTime\030\004 \001(\004\022\027\n\017ddwVa" +
      "lidEndTime\030\005 \001(\004\"-\n\017CJdZtReturnData\022\014\n\004i" +
      "Ret\030\001 \002(\005\022\014\n\004sMsg\030\002 \002(\014\"K\n\024CJdZtMiniProg" +
      "ramResp\022\036\n\004oRet\030\001 \002(\0132\020.CJdZtReturnData\022" +
      "\023\n\013vOriginalId\030\002 \003(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CJdZtMiniProgramReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CJdZtMiniProgramReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CJdZtMiniProgramReq_descriptor,
              new String[] { "VData", });
          internal_static_CJdZtMiniProgramData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CJdZtMiniProgramData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CJdZtMiniProgramData_descriptor,
              new String[] { "SOriginalId", "SAppId", "SAccessToken", "DdwValidBeginTime", "DdwValidEndTime", });
          internal_static_CJdZtReturnData_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_CJdZtReturnData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CJdZtReturnData_descriptor,
              new String[] { "IRet", "SMsg", });
          internal_static_CJdZtMiniProgramResp_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_CJdZtMiniProgramResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CJdZtMiniProgramResp_descriptor,
              new String[] { "ORet", "VOriginalId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
